# Generated by Django 4.2.4 on 2023-08-28 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_chat_message_user_delete_room_message_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chat',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
